### ISSUE TITLE
Training a new LSTM SpeechLM

### ISSUE THREAD

**Issue by ecooper7** [soumimaiti/speechlmscore_tool#3]
Hello, thank you for the nice paper and for sharing your code  :)

I am interested in training a new LSTM LM using some data which I have already prepared (I've got train/test/valid.txt files with the audio sample name followed by the sequence of KMeans cluster IDs already).  I was a bit unsure about the next steps in `Training.md` -- in Step 3, `run_lm.sh` refers to an `./asr.sh` -- where can I find this?  (I am assuming it comes from ESPnet, but I am less familiar and there seem to be several files called asr.sh in that repo -- which one should I use, and do I simply copy it into the `speechlmscore_tool` directory, or do I need to run it from inside of ESPnet?)  Any info or pointers would be greatly appreciated.  Thanks very much!

**Comment by ecooper7** [comment]
I seem to have got it working and I will document it here in case others are also wondering:
 * I installed Kaldi since it is a dependency for ESPnet (I didn't check carefully whether it's actually needed for this use case)
 * I installed ESPnet and symlinked Kaldi according to the instructions 
 * In `espnet/egs2` I did `mkdir my_slms` then `cd my_slms` then `cp -r ../TEMPLATE/asr1 .`
 * `cd asr1` and then the `data` dir with `token_list`, `[train,valid,test].txt` should be placed there, as well as the `conf` dir with the example conf file, and `run_lm.sh`, and the `dump` directory should all go here in `asr1` -- basically everything referenced in `Training.md` should go here in this `asr1` directory.
 * I was then able to run `run_lm.sh`
 * The trained LM is I think the one in `exp/lm_train_lm_rnn_unit1024_nlayers3_dropout0.2_epoch30_word/valid.loss.best.pth`
 * I was then able to point speechLMscore's perplexity script to this model path and get new perplexities.

**Comment by sw005320** [comment]
Thanks, @ecooper7!

@Takaaki-Saeki and @soumimaiti, can you incorporate this procedure in the document https://github.com/soumimaiti/speechlmscore_tool/blob/main/Training.md?

**Comment by ecooper7** [comment]
Thanks! 

I just wanted to confirm one more thing -- as for the format of the [train,valid,test].txt files, I think they should be the same as the format of the ${data_dir}/${split}.txt file that is output by run.sh (containing filename followed by kmeans IDs), is this correct?  Everything ran without errors so I am assuming it was ok, but I just wanted to confirm.

**Comment by soumimaiti** [comment]
Hi @ecooper7 You are correct, train/valid/test files should have format of <filename> <discrete kmean ids>. Discrete ids are space separated. 

It is generated by the output of run.sh
